### ISSUE TITLE
Tuple Supports?

### ISSUE THREAD

**Issue by op8867555** [alexkazik/ownable#6]
Hi, I'm trying do something like:
```rust
#[derive(ToOwned)]
struct S {
  xs: Vec<(Cow<'a, str>, usize)>
}
```
but it failed with a `(Cow<'_, str>, u8): ToOwned is not satisfied`,
simply add `#[ownable(clone)]` reports `a lifetime may not live long enough`.
Is there any way to works with tuples?

**Comment by alexkazik** [comment]
Good point, must have missed that in my tests. I'll try to add it soon.

(And `#[ownable(clone)]` does only work for things without a lifetime.)

**Comment by alexkazik** [comment]
I've just released a new version with tuple support - hope that helps.

**Comment by op8867555** [comment]
Just tried the latest version, it works as expected.
Thanks a lots for your quickly response & helping. 😄

**Comment by alexkazik** [comment]
I'm happy to help.
